--- #YAML:1.0
name: Posy-Plugin-DynamicCss
version: 0.40
author:
  - Kathryn Andersen
abstract: |-
  Posy plugin to load different CSS styles based on the UserAgent.
license: perl
requires:
  Posy: 0.4
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::DynamicCss:
    file: lib/Posy/Plugin/DynamicCss.pm
    version: 0.40
generated_by: Module::Build version 0.2607
