--- #YAML:1.0
name: Posy-Plugin-DynamicCss
version: 0.42
author:
  - Kathryn Andersen
abstract: |-
  Posy plugin to load different CSS styles based on the UserAgent.
license: gpl
requires:
  Posy: 0.95
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::DynamicCss:
    file: lib/Posy/Plugin/DynamicCss.pm
    version: 0.42
generated_by: Module::Build version 0.261
